#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""The web app's colour tokens, from the device's palettes (felucca/tools/gen_ui_palettes.py).

  gen_tokens.py OUT.css [--check] [--report] [--palettes PATH]

PATH: the device's palette table, tools/gen_ui_palettes.py (default: ../tools/ next to this file;
or FELUCCA_PALETTES). The web app may live apart from the firmware: it then names the firmware's copy.

The editor has two palettes: GREY (dark, the device's) and LIGHT (light, the editor's own: GREY's
black and white turned over, no hue), chosen by the OS setting (prefers-color-scheme) or by
data-theme="dark" / "light" on <html>. Both are derived with the device's maths (gen_ui_palettes.derive,
after RGB565), and both are grey: R = G = B, REC is ACCENT. The colours are not written by hand anywhere
else. Every text pairing the web uses is checked against WCAG AA (WEB_CHECKS); a miss fails the tool.
--check compares OUT.css with what this would write.
"""
import sys
from pathlib import Path

import importlib.util
import os


def palettes_source():
    a = sys.argv
    p = a[a.index("--palettes") + 1] if "--palettes" in a else os.environ.get("FELUCCA_PALETTES") or \
        str(Path(__file__).resolve().parent.parent / "tools" / "gen_ui_palettes.py")
    if not Path(p).exists():
        raise SystemExit(f"gen_tokens.py: no palette table at {p} (pass --palettes PATH to tools/gen_ui_palettes.py)")
    spec = importlib.util.spec_from_file_location("gen_ui_palettes", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


gp = palettes_source()

DARK, LIGHT = "GREY", "LIGHT"
# the editor's own light palette (not on the device): name, bg, surf, text, theme, accent
EDITOR_PALETTES = [("LIGHT", (240, 240, 240), (228, 228, 228), (40, 40, 40), (16, 16, 16), (0, 0, 0))]
# (foreground, background, minimum): the web's text pairings, WCAG AA for text (4.5) unless noted
WEB_CHECKS = [("text", "bg", 7.0), ("text", "surf", 7.0), ("text", "raise", 4.5), ("mid", "bg", 4.5),
              ("mid", "surf", 4.5), ("theme", "bg", 4.5), ("theme", "surf", 4.5), ("accent", "bg", 4.5),
              ("accent", "surf", 4.5), ("ink", "theme", 4.5), ("ink", "accent", 4.5), ("bg", "mid", 4.5)]
# CSS name -> derive() key
TOKENS = [("bg", "bg"), ("surf", "surf"), ("text", "text"), ("theme", "theme"), ("accent", "accent"),
          ("mid", "mid"), ("dim", "dim"), ("line", "line"), ("sel", "sel"), ("tint", "tint"),
          ("raise", "raise_"), ("key", "key"), ("ink", "ink"), ("rec", "rec")]


def palette(name):
    for p in gp.PALETTES + EDITOR_PALETTES:
        if p[0] == name:
            d = gp.derive(p)[1]
            d["rec"] = d["accent"]             # grey palettes: REC is ACCENT (as GREY on the device)
            return d
    raise SystemExit(f"no palette {name}")


def lum(hexc):
    def lin(v):
        v /= 255.0
        return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = (int(hexc[i:i + 2], 16) for i in (1, 3, 5))
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def contrast(a, b):
    la, lb = lum(a), lum(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)


def tokens(name):
    d = palette(name)
    return {css: hexof(d[key], True) for css, key in TOKENS}


def check():
    """the web's text pairings in both palettes; returns the misses"""
    miss = []
    for name in (DARK, LIGHT):
        t = tokens(name)
        for fg, bg, need in WEB_CHECKS:
            c = contrast(t[fg], t[bg])
            if c < need:
                miss.append(f"{name} {fg}/{bg} {c:.2f} < {need}")
    return miss


def hexof(c565, grey=False):
    r, g, b = gp.from565(c565)
    if grey:                           # GREY sits on the RGB565 grey axis (G = 2 R): on the web, R = G = B
        g = b = r
    return f"#{r:02x}{g:02x}{b:02x}"


def block(name):
    d = palette(name)
    lines = [f"  --{css}: {v};" for css, v in tokens(name).items()]
    lines.append(f"  color-scheme: {'light' if d['light'] else 'dark'};")
    return "\n".join(lines)


def css():
    head = ("/* SPDX-License-Identifier: GPL-3.0-only\n"
            " * Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments */\n"
            f"/* generated by felucca/web/gen_tokens.py from tools/gen_ui_palettes.py ({DARK} / {LIGHT}): do not edit */\n")
    dark, light = block(DARK), block(LIGHT)
    return (head +
            f":root {{\n{dark}\n}}\n"
            f"@media (prefers-color-scheme: light) {{\n  :root:not([data-theme=\"dark\"]) {{\n"
            + "\n".join("  " + x for x in light.split("\n")) + "\n  }\n}\n"
            f":root[data-theme=\"light\"] {{\n{light}\n}}\n"
            f":root[data-theme=\"dark\"] {{\n{dark}\n}}\n")


def main():
    argv = sys.argv[1:]
    if "--palettes" in argv:
        k = argv.index("--palettes")
        del argv[k:k + 2]
    args = [a for a in argv if not a.startswith("--")]
    if len(args) != 1:
        raise SystemExit(__doc__)
    miss = check()
    if miss:
        raise SystemExit("contrast: " + "; ".join(miss))
    if "--report" in sys.argv:
        for name in (DARK, LIGHT):
            t = tokens(name)
            print(name, " ".join(f"{fg}/{bg} {contrast(t[fg], t[bg]):.2f}" for fg, bg, _ in WEB_CHECKS))
    out, text = Path(args[0]), css()
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != text:
            raise SystemExit(f"{out} is stale: run gen_tokens.py {out}")
        return
    out.write_text(text)


if __name__ == "__main__":
    main()
