#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""The parameter icons of the device, for the web app: label -> Fukiai glyph name.

  gen_icons.py OUT.js [--check] [--firmware DIR]

DIR: a Felucca checkout's felucca/ (default: the folder above this file, or FELUCCA_FIRMWARE). Read:
src/icons.c (ICON_MAP: label -> ICON_*, WAVE_ICON: a wave's name -> ICON_*) and tools/gen_aa_icons.py
(LEGACY / EXTRA: the icon's name -> the glyph, a tuple = the first the font has), and the MOD matrix's
mod_src_icon / mod_dst_icon. So a parameter shows the
icon the device draws for it. --check compares OUT.js with what this would write.
"""
import ast
import json
import os
import re
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent


def firmware_dir():
    a = sys.argv
    d = a[a.index("--firmware") + 1] if "--firmware" in a else os.environ.get("FELUCCA_FIRMWARE") or str(HERE.parent)
    d = Path(d)
    if not (d / "src" / "icons.c").exists() or not (d / "tools" / "gen_aa_icons.py").exists():
        raise SystemExit(f"gen_icons.py: no src/icons.c and tools/gen_aa_icons.py in {d} (pass --firmware DIR, Felucca's felucca/)")
    return d


def dicts(py):
    """the LEGACY and EXTRA dict literals of gen_aa_icons.py (read, not run)"""
    out = {}
    for node in ast.parse(py.read_text()).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and getattr(node.targets[0], "id", "") in ("LEGACY", "EXTRA"):
            out.update(ast.literal_eval(node.value))
    return out


def table(fw):
    cmap = {name for name in TTFont(str(HERE / "fukiai.ttf")).getBestCmap().values()}
    names = dicts(fw / "tools" / "gen_aa_icons.py")
    pick = lambda g: next((x for x in g if x in cmap), None) if isinstance(g, tuple) else (g if g in cmap else None)
    glyph = {"ICON_" + k.upper(): pick(v) for k, v in names.items()}
    src = (fw / "src" / "icons.c").read_text()
    def block(name):
        m = re.search(r"static const icon_map_t " + name + r"\[\] = \{(.*?)\n\};", src, re.S)
        if not m:
            raise SystemExit(f"gen_icons.py: no {name} in icons.c")
        body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
        body = re.sub(r"#if[^\n]*\n|#endif[^\n]*\n|#else[^\n]*\n", "", body)
        return [(lab, ic) for lab, ic in re.findall(r'\{"([^"]+)",\s*(ICON_\w+)\}', body)]
    labels, waves, missing = {}, {}, []
    for lab, ic in block("ICON_MAP"):
        if lab in labels:
            continue                                   # (the first wins, as icon_for_label's search)
        if glyph.get(ic):
            labels[lab] = glyph[ic]
        else:
            missing.append(ic)
    for lab, ic in block("WAVE_ICON"):
        if glyph.get(ic):
            waves[lab] = glyph[ic]
    def arr(fn):
        m = re.search(r"static uint32_t " + fn + r"\(.*?static const uint8_t I\[\w+\] = \{(.*?)\};", src, re.S)
        if not m:
            raise SystemExit(f"gen_icons.py: no {fn} table in icons.c")
        return [glyph.get(ic) or glyph.get("ICON_GENERIC") for ic in re.findall(r"ICON_\w+", m.group(1))]
    mods = {"src": arr("mod_src_icon"), "dst": arr("mod_dst_icon")}
    special = {k: glyph.get(k) for k in ("ICON_LFO_WAVE", "ICON_DIVISION", "ICON_CUTOFF", "ICON_NOISE", "ICON_RATE",
                                          "ICON_SLICE", "ICON_GATE", "ICON_ORDER", "ICON_GENERIC")}
    return labels, waves, special, mods, sorted(set(missing))


def js(fw):
    labels, waves, special, mods, missing = table(fw)
    q = lambda d: "{\n" + "".join(f'  {k!r}: {v!r},\n'.replace("'", '"') for k, v in d.items()) + "}"
    return ("// SPDX-License-Identifier: GPL-3.0-only\n"
            "// Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments\n"
            "// generated by gen_icons.py from the firmware's src/icons.c and tools/gen_aa_icons.py: do not edit\n"
            f"export const BY_LABEL = {q(labels)};\n"
            f"export const BY_WAVE = {q(waves)};\n"
            f"export const SPECIAL = {q(special)};\n"
            "/* the MOD matrix: a source's icon by its value, a destination's (before E1..E8: those are the engine's own) */\n"
            f"export const MOD_SRC = {json.dumps(mods['src'])};\n"
            f"export const MOD_DST = {json.dumps(mods['dst'])};\n"), missing


def main():
    argv = sys.argv[1:]
    if "--firmware" in argv:
        k = argv.index("--firmware")
        del argv[k:k + 2]
    args = [a for a in argv if not a.startswith("--")]
    if len(args) != 1:
        raise SystemExit(__doc__)
    text, missing = js(firmware_dir())
    if missing:
        print("gen_icons.py: icons with no glyph in fukiai.ttf (left to the generic one):", " ".join(missing), file=sys.stderr)
    out = Path(args[0])
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != text:
            raise SystemExit(f"{out} is stale: run gen_icons.py {out}")
        return
    out.write_text(text)


if __name__ == "__main__":
    main()
