#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""The Fukiai glyph table for the web app: name -> codepoint, read from fukiai.ttf's cmap.

  gen_glyphs.py OUT.js [--check]

The page names icons by glyph name (as the device's tools/gen_aa_icons.py does); this table is the only
place codepoints appear, so a font update needs only a rerun. --check compares OUT.js with what this would write.
"""
import sys
from pathlib import Path

from fontTools.ttLib import TTFont


def table():
    cmap = TTFont(str(Path(__file__).resolve().parent / "fukiai.ttf")).getBestCmap()
    names = {}
    for cp, name in sorted(cmap.items()):
        if 0xE000 <= cp <= 0xF8FF and not name.startswith("glyph"):
            names.setdefault(name, cp)
    return names


def js():
    rows = [f"  {n}: 0x{cp:04X}," for n, cp in sorted(table().items())]
    return ("// SPDX-License-Identifier: GPL-3.0-only\n"
            "// Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments\n"
            "// generated by felucca/web/gen_glyphs.py from fukiai.ttf: do not edit\n"
            "export const GLYPH = {\n" + "\n".join(rows) + "\n};\n")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        raise SystemExit(__doc__)
    out, text = Path(args[0]), js()
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != text:
            raise SystemExit(f"{out} is stale: run gen_glyphs.py {out}")
        return
    out.write_text(text)


if __name__ == "__main__":
    main()
